"""002 - Adding tables FII, FIIType and FIIDividend

Revision ID: 33ca34a7a143
Revises: 901b123e9329
Create Date: 2022-08-07 13:42:58.371901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33ca34a7a143'
down_revision = '901b123e9329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fii_type',
    sa.Column('pk', sa.BigInteger(), nullable=False),
    sa.Column('rm_timestamp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('name', sa.Unicode(length=50), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_fii_type_pk'), 'fii_type', ['pk'], unique=False)
    op.create_table('fii',
    sa.Column('pk', sa.BigInteger(), nullable=False),
    sa.Column('rm_timestamp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fii_type_pk', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.Column('code', sa.Unicode(length=10), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['fii_type_pk'], ['fii_type.pk'], name='fii_fii_type_pk_fk'),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_fii_fii_type_pk'), 'fii', ['fii_type_pk'], unique=False)
    op.create_index(op.f('ix_fii_pk'), 'fii', ['pk'], unique=False)
    op.create_table('fii_dividend',
    sa.Column('pk', sa.BigInteger(), nullable=False),
    sa.Column('rm_timestamp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fii_pk', sa.BigInteger(), nullable=False),
    sa.Column('base_date', sa.DateTime(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('base_quotation', sa.Float(), nullable=False),
    sa.Column('dividend_yield', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['fii_pk'], ['fii.pk'], name='fii_dividend_fii_pk_fk'),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_fii_dividend_base_date'), 'fii_dividend', ['base_date'], unique=False)
    op.create_index(op.f('ix_fii_dividend_fii_pk'), 'fii_dividend', ['fii_pk'], unique=False)
    op.create_index(op.f('ix_fii_dividend_payment_date'), 'fii_dividend', ['payment_date'], unique=False)
    op.create_index(op.f('ix_fii_dividend_pk'), 'fii_dividend', ['pk'], unique=False)
    op.drop_index('ix_share_pk', table_name='share')
    op.drop_table('share')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share',
    sa.Column('pk', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('rm_timestamp', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('pk', name='share_pkey')
    )
    op.create_index('ix_share_pk', 'share', ['pk'], unique=False)
    op.drop_index(op.f('ix_fii_dividend_pk'), table_name='fii_dividend')
    op.drop_index(op.f('ix_fii_dividend_payment_date'), table_name='fii_dividend')
    op.drop_index(op.f('ix_fii_dividend_fii_pk'), table_name='fii_dividend')
    op.drop_index(op.f('ix_fii_dividend_base_date'), table_name='fii_dividend')
    op.drop_table('fii_dividend')
    op.drop_index(op.f('ix_fii_pk'), table_name='fii')
    op.drop_index(op.f('ix_fii_fii_type_pk'), table_name='fii')
    op.drop_table('fii')
    op.drop_index(op.f('ix_fii_type_pk'), table_name='fii_type')
    op.drop_table('fii_type')
    # ### end Alembic commands ###
