"""006 - Creatign table to register the FII shares I bought. Also fixing volume type from the fii_quotation table

Revision ID: 5da14ac57e61
Revises: a8b39dd09a51
Create Date: 2022-08-14 12:04:39.873818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5da14ac57e61'
down_revision = 'a8b39dd09a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fii_share',
    sa.Column('pk', sa.BigInteger(), nullable=False),
    sa.Column('rm_timestamp', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('fii_pk', sa.BigInteger(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fii_pk'], ['fii.pk'], name='fii_share_fii_pk_fk'),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_fii_share_fii_pk'), 'fii_share', ['fii_pk'], unique=False)
    op.create_index(op.f('ix_fii_share_pk'), 'fii_share', ['pk'], unique=False)
    op.create_index(op.f('ix_fii_share_purchase_date'), 'fii_share', ['purchase_date'], unique=False)
    op.alter_column('fii_quotation', 'volume',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fii_quotation', 'volume',
               existing_type=sa.Integer(),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_index(op.f('ix_fii_share_purchase_date'), table_name='fii_share')
    op.drop_index(op.f('ix_fii_share_pk'), table_name='fii_share')
    op.drop_index(op.f('ix_fii_share_fii_pk'), table_name='fii_share')
    op.drop_table('fii_share')
    # ### end Alembic commands ###
