"""001 - First migration to test alembic

Revision ID: 901b123e9329
Revises: 
Create Date: 2022-08-06 23:41:47.800909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901b123e9329'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share',
    sa.Column('pk', sa.BigInteger(), nullable=False),
    sa.Column('rm_timestamp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_share_pk'), 'share', ['pk'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_pk'), table_name='share')
    op.drop_table('share')
    # ### end Alembic commands ###
