"""003 - Adding unique constraints to the tables FII, FIIType and FIIDividend

Revision ID: c793a97d4ba5
Revises: 33ca34a7a143
Create Date: 2022-08-07 16:51:49.719976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c793a97d4ba5'
down_revision = '33ca34a7a143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('fii_code_un', 'fii', ['code', 'rm_timestamp'])
    op.create_unique_constraint('fii_name_un', 'fii', ['name', 'rm_timestamp'])
    op.create_unique_constraint('fii_dividend_base_date_fii_pk_un', 'fii_dividend', ['base_date', 'fii_pk', 'rm_timestamp'])
    op.create_unique_constraint('fii_dividend_payment_date_fii_pk_un', 'fii_dividend', ['payment_date', 'fii_pk', 'rm_timestamp'])
    op.create_unique_constraint('fii_type_rm_timestamp_un', 'fii_type', ['name', 'rm_timestamp'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fii_type_rm_timestamp_un', 'fii_type', type_='unique')
    op.drop_constraint('fii_dividend_payment_date_fii_pk_un', 'fii_dividend', type_='unique')
    op.drop_constraint('fii_dividend_base_date_fii_pk_un', 'fii_dividend', type_='unique')
    op.drop_constraint('fii_name_un', 'fii', type_='unique')
    op.drop_constraint('fii_code_un', 'fii', type_='unique')
    # ### end Alembic commands ###
